kind = "web"
previewPath = "/"
title = "Marrymap"
version = "1.0.0"
id = "artifacts/marrymap"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23676

[services.development]
run = "pnpm --filter @workspace/marrymap run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/marrymap", "run", "build" ]
serve = "static"
publicDir = "artifacts/marrymap/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23676"
BASE_PATH = "/"
